// flow-typed signature: 28957f4b8a3d6bcddef036c32739b207
// flow-typed version: <<STUB>>/grunt-text-replace_v^0.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-text-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-text-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-text-replace/Gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-text-replace/lib/grunt-text-replace' {
  declare module.exports: any;
}

declare module 'grunt-text-replace/tasks/text-replace' {
  declare module.exports: any;
}

declare module 'grunt-text-replace/test/text-replace-error-tests' {
  declare module.exports: any;
}

declare module 'grunt-text-replace/test/text-replace-functional-tests' {
  declare module.exports: any;
}

declare module 'grunt-text-replace/test/text-replace-unit-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-text-replace/Gruntfile.js' {
  declare module.exports: $Exports<'grunt-text-replace/Gruntfile'>;
}
declare module 'grunt-text-replace/lib/grunt-text-replace.js' {
  declare module.exports: $Exports<'grunt-text-replace/lib/grunt-text-replace'>;
}
declare module 'grunt-text-replace/tasks/text-replace.js' {
  declare module.exports: $Exports<'grunt-text-replace/tasks/text-replace'>;
}
declare module 'grunt-text-replace/test/text-replace-error-tests.js' {
  declare module.exports: $Exports<'grunt-text-replace/test/text-replace-error-tests'>;
}
declare module 'grunt-text-replace/test/text-replace-functional-tests.js' {
  declare module.exports: $Exports<'grunt-text-replace/test/text-replace-functional-tests'>;
}
declare module 'grunt-text-replace/test/text-replace-unit-tests.js' {
  declare module.exports: $Exports<'grunt-text-replace/test/text-replace-unit-tests'>;
}
