// flow-typed signature: 2accb303ee04e6cce1a010d9b6cf6f91
// flow-typed version: <<STUB>>/karma-expect_v^1.1.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-expect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-expect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-expect/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-expect/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-expect/index' {
  declare module.exports: $Exports<'karma-expect'>;
}
declare module 'karma-expect/index.js' {
  declare module.exports: $Exports<'karma-expect'>;
}
declare module 'karma-expect/karma.conf.js' {
  declare module.exports: $Exports<'karma-expect/karma.conf'>;
}
declare module 'karma-expect/test/spec.js' {
  declare module.exports: $Exports<'karma-expect/test/spec'>;
}
